"""enum changed

Revision ID: 0cd1931b6fae
Revises: 7767162ee1b3
Create Date: 2026-08-22 18:00:36.712667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cd1931b6fae'
down_revision = '7767162ee1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=postgresql.ENUM('cash', 'upi', 'cheque', name='methodenum'),
               type_=sa.Enum('cash', 'upi', 'cheque', name='methodenum', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'expired', 'cancelled', name='statusenum'),
               type_=sa.Enum('pending', 'completed', 'confirmed', 'expired', 'cancelled', name='statusenum', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('open', 'complete', 'cancelled', name='pledgestatusenum'),
               type_=sa.Enum('open', 'complete', 'cancelled', name='pledgestatusenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'complete', 'cancelled', name='pledgestatusenum', native_enum=False),
               type_=postgresql.ENUM('open', 'complete', 'cancelled', name='pledgestatusenum'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'completed', 'confirmed', 'expired', 'cancelled', name='statusenum', native_enum=False),
               type_=postgresql.ENUM('pending', 'confirmed', 'expired', 'cancelled', name='statusenum'),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.Enum('cash', 'upi', 'cheque', name='methodenum', native_enum=False),
               type_=postgresql.ENUM('cash', 'upi', 'cheque', name='methodenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
