"""change in app config

Revision ID: 1438418bec27
Revises: d0be74337563
Create Date: 2026-10-05 13:39:37.709285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438418bec27'
down_revision = 'd0be74337563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key', name='uq_app_config_org_key')
    )
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_org_id'))

    op.drop_table('app_config')
    # ### end Alembic commands ###
