"""change in contribution

Revision ID: 227e517d5e17
Revises: 72bb82e67bb1
Create Date: 2026-10-05 17:13:25.007836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227e517d5e17'
down_revision = '72bb82e67bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution_slips', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution_slips', schema=None) as batch_op:
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
