"""change in contribution

Revision ID: 287213a32a8a
Revises: 5ef8806c04b3
Create Date: 2026-10-05 17:36:17.279611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287213a32a8a'
down_revision = '5ef8806c04b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=125),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.String(length=125),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
