"""change in user creation

Revision ID: 3f3ec035f437
Revises: a3a58247e7b4
Create Date: 2026-10-02 16:57:36.069100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3ec035f437'
down_revision = 'a3a58247e7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('member_since', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('member_since')
        batch_op.drop_column('member_category')

    # ### end Alembic commands ###
