"""performance scalling

Revision ID: 4090fede62c5
Revises: f026d5727392
Create Date: 2026-09-30 13:55:28.624043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4090fede62c5'
down_revision = 'f026d5727392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('circulars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circulars_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_circulars_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_donor_id'), ['donor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_event_id'))
        batch_op.drop_index(batch_op.f('ix_payments_donor_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_collector_id'))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_event_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_created_by'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_event_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_by'))

    with op.batch_alter_table('circulars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circulars_event_id'))
        batch_op.drop_index(batch_op.f('ix_circulars_created_by'))

    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_created_by'))

    # ### end Alembic commands ###
