"""change in permissions

Revision ID: 42fe593cb5ee
Revises: 62fa84776fff
Create Date: 2026-10-06 23:13:28.648002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fe593cb5ee'
down_revision = '62fa84776fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=210),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=210),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
