"""user model change

Revision ID: 4558b0ead766
Revises: 960fec5325ef
Create Date: 2026-08-23 14:29:08.187280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4558b0ead766'
down_revision = '960fec5325ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('whatsapp_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'executive', 'committee', 'general', name='roleenum'),
               type_=sa.Enum('admin', 'managing_committee', 'core_committee', 'executive', 'cashier', 'collector', 'committee', 'general', name='roleenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'managing_committee', 'core_committee', 'executive', 'cashier', 'collector', 'committee', 'general', name='roleenum', native_enum=False),
               type_=postgresql.ENUM('admin', 'executive', 'committee', 'general', name='roleenum'),
               existing_nullable=False)
        batch_op.alter_column('whatsapp_no',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('address')

    # ### end Alembic commands ###
