"""change in payement handover

Revision ID: 4ff4705877f2
Revises: 86dd0e498b95
Create Date: 2026-10-03 01:34:35.212694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff4705877f2'
down_revision = '86dd0e498b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('handover_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='handoverstatusenum', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handovers_collector_id'), ['collector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handovers_status'))
        batch_op.drop_index(batch_op.f('ix_handovers_org_id'))
        batch_op.drop_index(batch_op.f('ix_handovers_event_id'))
        batch_op.drop_index(batch_op.f('ix_handovers_created_at'))
        batch_op.drop_index(batch_op.f('ix_handovers_collector_id'))

    op.drop_table('handovers')
    # ### end Alembic commands ###
