"""token

Revision ID: 57fdac774c0b
Revises: 007877994c33
Create Date: 2026-08-22 09:36:12.006026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fdac774c0b'
down_revision = '007877994c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_no', sa.String(length=60), nullable=False),
    sa.Column('token_serial', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single', 'dual', 'bulk', name='tokentypeenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'void', name='tokenstatusenum'), nullable=False),
    sa.Column('participant_name', sa.String(length=120), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
