"""change in contribution

Revision ID: 5ef8806c04b3
Revises: 227e517d5e17
Create Date: 2026-10-05 17:16:01.109430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef8806c04b3'
down_revision = '227e517d5e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handover_to_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_handovers_handover_to_id'), ['handover_to_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['handover_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_handovers_handover_to_id'))
        batch_op.drop_column('handover_to_id')

    # ### end Alembic commands ###
