"""change in permissions

Revision ID: 62fa84776fff
Revises: c3e02ce10929
Create Date: 2026-10-06 22:57:10.881854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fa84776fff'
down_revision = 'c3e02ce10929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_cashier', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.drop_column('can_cashier')

    # ### end Alembic commands ###
