"""change in contribution

Revision ID: 72bb82e67bb1
Revises: 1438418bec27
Create Date: 2026-10-05 16:23:38.010063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bb82e67bb1'
down_revision = '1438418bec27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slip_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_self_contributions_slip_id'), ['slip_id'], unique=False)
        batch_op.create_foreign_key(None, 'contribution_slips', ['slip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_contributions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_self_contributions_slip_id'))
        batch_op.drop_column('slip_id')

    # ### end Alembic commands ###
