"""pledger

Revision ID: 7767162ee1b3
Revises: fd62228efa4a
Create Date: 2026-08-22 15:04:57.886676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7767162ee1b3'
down_revision = 'fd62228efa4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'complete', 'cancelled', name='pledgestatusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheque_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cheque_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pledge_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pledges', ['pledge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pledge_id')
        batch_op.drop_column('cheque_date')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('cheque_number')

    op.drop_table('pledges')
    # ### end Alembic commands ###
