"""event active

Revision ID: 805fda5937e8
Revises: 2db141b3a126
Create Date: 2026-08-23 22:00:54.935217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '805fda5937e8'
down_revision = '2db141b3a126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'executive', 'committee', 'general', name='roleenum'),
               type_=sa.Enum('admin', 'managing_committee', 'core_committee', 'executive', 'cashier', 'collector', 'committee', 'general', name='roleenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'managing_committee', 'core_committee', 'executive', 'cashier', 'collector', 'committee', 'general', name='roleenum', native_enum=False),
               type_=postgresql.ENUM('admin', 'executive', 'committee', 'general', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
