"""change in payement collection major

Revision ID: 86dd0e498b95
Revises: 98900e26d49e
Create Date: 2026-10-03 01:01:41.622268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dd0e498b95'
down_revision = '98900e26d49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_slip_id'), ['slip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_slip_id'))

    # ### end Alembic commands ###
