"""query added

Revision ID: 960fec5325ef
Revises: ac0c042fb5bd
Create Date: 2026-08-23 12:05:47.115081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960fec5325ef'
down_revision = 'ac0c042fb5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'read', 'resolved', name='contactquerystatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_queries')
    # ### end Alembic commands ###
