"""change in commete and role

Revision ID: 98900e26d49e
Revises: eebac5b5caf1
Create Date: 2026-10-02 23:26:02.852538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98900e26d49e'
down_revision = 'eebac5b5caf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'label', name='uq_club_year_org_label')
    )
    with op.batch_alter_table('club_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_years_org_id'), ['org_id'], unique=False)

    op.create_table('year_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('club_year_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'junior_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['club_year_id'], ['club_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_year_id', 'user_id', name='uq_year_role_year_user')
    )
    with op.batch_alter_table('year_role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_year_role_assignments_club_year_id'), ['club_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_year_role_assignments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_year_role_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('event_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'junior_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False), nullable=False),
    sa.Column('can_collect', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_role_event_user')
    )
    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_role_assignments_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_role_assignments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_role_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_role_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_role_assignments_org_id'))
        batch_op.drop_index(batch_op.f('ix_event_role_assignments_event_id'))

    op.drop_table('event_role_assignments')
    with op.batch_alter_table('year_role_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_year_role_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_year_role_assignments_org_id'))
        batch_op.drop_index(batch_op.f('ix_year_role_assignments_club_year_id'))

    op.drop_table('year_role_assignments')
    with op.batch_alter_table('club_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_years_org_id'))

    op.drop_table('club_years')
    # ### end Alembic commands ###
