"""test

Revision ID: 99173e6b66e7
Revises: 4558b0ead766
Create Date: 2026-08-23 16:30:46.792535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99173e6b66e7'
down_revision = '4558b0ead766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atd_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'session_number', name='uq_atd_session_date_num'),
    sa.UniqueConstraint('qr_token')
    )
    with op.batch_alter_table('atd_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atd_sessions_date'), ['date'], unique=False)

    op.create_table('atd_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['atd_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'device_fingerprint', name='uq_atd_record_session_device'),
    sa.UniqueConstraint('session_id', 'phone', name='uq_atd_record_session_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atd_records')
    with op.batch_alter_table('atd_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atd_sessions_date'))

    op.drop_table('atd_sessions')
    # ### end Alembic commands ###
