"""fresh

Revision ID: a3a58247e7b4
Revises: 
Create Date: 2026-09-30 16:52:19.185144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a58247e7b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('budget_notes')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('budget_notes', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
