"""change in ordering

Revision ID: c3e02ce10929
Revises: 2d42dfd62072
Create Date: 2026-10-06 15:59:00.738119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e02ce10929'
down_revision = '2d42dfd62072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_orderings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'scope_id', 'user_id', name='uq_committee_order_scope_user')
    )
    with op.batch_alter_table('committee_orderings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_orderings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_orderings_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_orderings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee_orderings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_orderings_user_id'))
        batch_op.drop_index(batch_op.f('ix_committee_orderings_scope_id'))
        batch_op.drop_index(batch_op.f('ix_committee_orderings_org_id'))

    op.drop_table('committee_orderings')
    # ### end Alembic commands ###
