"""change for meeting and action plan

Revision ID: c78919ee0a62
Revises: facec7e61b56
Create Date: 2026-09-16 01:37:58.778536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78919ee0a62'
down_revision = 'facec7e61b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('meeting_type', sa.Enum('general', 'emergency', 'committee', 'agm', 'other', name='meetingtypeenum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'in_progress', 'completed', 'cancelled', name='meetingstatusenum', native_enum=False), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='actionplanpriorityenum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'on_hold', 'cancelled', name='actionplanstatusenum', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plans_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plans_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'tabled', name='agendaitemstatusenum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_agenda_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_agenda_items_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_attendance')
    )
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_attendance_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_attendance_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'device_token', name='uq_meeting_device')
    )
    with op.batch_alter_table('meeting_attendance_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_attendance_devices_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_invitees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invitation_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_invitee')
    )
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_invitees_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('action_plan_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_plan_id', 'user_id', name='uq_action_plan_assignee')
    )
    with op.batch_alter_table('action_plan_assignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plan_assignees_action_plan_id'), ['action_plan_id'], unique=False)

    op.create_table('meeting_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_visible_to_members', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['meeting_agenda_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_discussions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_discussions_agenda_item_id'), ['agenda_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_discussions_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_discussions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_discussions_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_discussions_agenda_item_id'))

    op.drop_table('meeting_discussions')
    with op.batch_alter_table('action_plan_assignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plan_assignees_action_plan_id'))

    op.drop_table('action_plan_assignees')
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_invitees_meeting_id'))

    op.drop_table('meeting_invitees')
    with op.batch_alter_table('meeting_attendance_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_devices_meeting_id'))

    op.drop_table('meeting_attendance_devices')
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_meeting_id'))

    op.drop_table('meeting_attendance')
    with op.batch_alter_table('meeting_agenda_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_agenda_items_meeting_id'))

    op.drop_table('meeting_agenda_items')
    with op.batch_alter_table('action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plans_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_action_plans_event_id'))

    op.drop_table('action_plans')
    op.drop_table('meetings')
    # ### end Alembic commands ###
