"""change in public site dynamic content

Revision ID: d0be74337563
Revises: 4ff4705877f2
Create Date: 2026-10-05 13:12:09.244882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0be74337563'
down_revision = '4ff4705877f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('app_config_key_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_app_config_org_id'), ['org_id'], unique=False)
        batch_op.create_unique_constraint('uq_app_config_org_key', ['org_id', 'key'])
        batch_op.create_foreign_key(None, 'organisations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_app_config_org_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_app_config_org_id'))
        batch_op.create_unique_constraint(batch_op.f('app_config_key_key'), ['key'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
