"""change in role rename

Revision ID: e2fd54867b4e
Revises: 42fe593cb5ee
Create Date: 2026-10-06 23:46:54.868102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fd54867b4e'
down_revision = '42fe593cb5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'joint_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('year_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'joint_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('year_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'joint_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('event_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('chairman', 'president', 'vice_president', 'secretary', 'joint_secretary', 'treasurer', 'accountant', 'advisory_member', 'member', name='committeeroleenum', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
