"""change in user member id

Revision ID: eebac5b5caf1
Revises: 3f3ec035f437
Create Date: 2026-10-02 17:38:41.102094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebac5b5caf1'
down_revision = '3f3ec035f437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_member_id'), ['member_id'], unique=False)
        batch_op.create_unique_constraint('uq_users_member_id_org', ['member_id', 'org_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_member_id_org', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_member_id'))
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
