"""org code

Revision ID: f026d5727392
Revises: b8b9f58dad87
Create Date: 2026-09-30 12:23:26.474264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f026d5727392'
down_revision = 'b8b9f58dad87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_provisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['org_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('org_code')

    with op.batch_alter_table('org_provisions', schema=None) as batch_op:
        batch_op.drop_column('org_code')

    # ### end Alembic commands ###
