"""change for self contribution feature

Revision ID: facec7e61b56
Revises: 805fda5937e8
Create Date: 2026-09-16 00:39:28.555702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facec7e61b56'
down_revision = '805fda5937e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'upi', 'bank_transfer', name='paymentmethodenum', native_enum=False), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_time', sa.String(length=10), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='contributionstatusenum', native_enum=False), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('self_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_self_contributions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_contributions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_contributions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('self_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_self_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_self_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_self_contributions_event_id'))

    op.drop_table('self_contributions')
    # ### end Alembic commands ###
