"""donar type added

Revision ID: fd62228efa4a
Revises: 57fdac774c0b
Create Date: 2026-08-22 14:46:06.663212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd62228efa4a'
down_revision = '57fdac774c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('donor_type')

    # ### end Alembic commands ###
